### ISSUE TITLE
"data/eff_large_wordlist.txt:  no such file or directory"

### ISSUE THREAD

**Issue by neilberkman** [r38y/eff-pass#1]
Thanks for creating this, it's exactly what I needed. However when I try to deploy my application to Gigalixir I'm getting this:

```
2021-02-09T04:49:25.873714+00:00 my_app[b'my_app-7d55dd7db9-9mhhk']: web.1 |  ** (File.Error) could not stream "/tmp/build/deps/eff_pass/data/eff_large_wordlist.txt": no such file or directory
```

I see that you're including the `data` directory in `files`. Any idea what might be going wrong? Thanks.

**Comment by r38y** [comment]
Hi Neil, and it works fine locally for you? 

On February 13, 2021, GitHub <notifications@github.com> wrote:
> Thanks for creating this, it's exactly what I needed. However when I

> try to deploy my application to Gigalixir I'm getting this:
>
> 2021-02-09T04:49:25.873714+00:00 my_app[b'my_app-7d55dd7db9-9mhhk']:

> web.1 | ** (File.Error) could not stream
> "/tmp/build/deps/eff_pass/data/eff_large_wordlist.txt": no such file

> or directory2021-02-09T04:49:25.873714+00:00 my_app[b'my_app-
> 7d55dd7db9-9mhhk']: web.1 | ** (File.Error) could not stream
> "/tmp/build/deps/eff_pass/data/eff_large_wordlist.txt": no such file

> or directory
> I see that you're including the data directory in files. Any idea what

> might be going wrong? Thanks.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/r38y/eff-pass/issues/1>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAAHHQ464OY2HKSL724L7TS63NGJANCNFSM4XSPBANQ>.
